### ISSUE TITLE
The Wheel

### ISSUE THREAD

**Issue by Randolphjand** [JamesLaFritz/GraphViewBehaviorTree#1]
Why re-invent the wheel?  The Kiwi Coder on Youtube made a behavior tree with toolkit and graphview.  The code for hooking up the nodes is already written and you can just adapt it to your tree.  Just an idea.

**Comment by JamesLaFritz** [comment]
I will check it out and see how much is the same and give him credit for
it.  I write articles on medium explaining concepts. The Code is more for
helping understand those concepts.
