### ISSUE TITLE
Will not install.

### ISSUE THREAD

**Issue by Randolphjand** [JamesLaFritz/GraphViewBehaviorTree#2]
I tried installing this package and tried just adding the files from the zip and it would not work.

**Comment by JamesLaFritz** [comment]
@Randolphjand what version of Unity are you using? Is there an error message that you are receiving?

**Comment by Randolphjand** [comment]
2022.1.3

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/JamesLaFritz/GraphViewBehaviorTree.git]:
  Manifest [E:\Unity\UI URP\Library\PackageCache\com.james.lafritz.GraphViewBehaviorTree@284484a46c\package.json] is invalid:
   Package name 'com.james.lafritz.GraphViewBehaviorTree' is invalid. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by JamesLaFritz** [comment]
https://github.com/JamesLaFritz/GraphViewBehaviorTree/commit/72de5ef7861bb86d9f0d5839c03901f79b2ccbfe

**Comment by JamesLaFritz** [comment]
see https://github.com/JamesLaFritz/GraphViewBehaviorTree/commit/72de5ef7861bb86d9f0d5839c03901f79b2ccbfe for fix

**Comment by JamesLaFritz** [comment]
@Randolphjand There was an extra period in the package json. Thank you for pointing out this issue. You should be good to try it now.

**Comment by Randolphjand** [comment]
Something strange is going on.  I guess you made it so the root node does not show up in the inspector?  I still get errors.
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <f4694e4600d74e03a4e35def8b97021c>:0)
GraphViewBehaviorTree.BehaviorTree.Clone () (at Library/PackageCache/com.jameslafritz.graphviewbehaviortree@d101e1a088/Runtime/BehaviorTree.cs:177)
GraphViewBehaviorTree.BehaviorTreeRunner.Start () (at Library/PackageCache/com.jameslafritz.graphviewbehaviortree@d101e1a088/Runtime/BehaviorTreeRunner.cs:33)

**Comment by JamesLaFritz** [comment]
Yes the root node is hidden in the inspector. It us designed to be setup
using the behavior tree editor. Double click on the behavior, or go to
Window Behavior Tree Editor. If you have the Game Object with a behavior
tree runner on it the Behavior Tree associated with that will be displayed
in the Editor Window.

The error that you are getting is because the tree has no children
associated with it.
